# -*- coding: utf-8 -*-
"""Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SWtSatIZJp2kqKAH-ISl9wwDGxUNcLN6
"""

from difflib import SequenceMatcher

with open(r"/content/1.txt") as file1,open(r"/content/1.txt") as file2:
  file1_data = file1.read()
  file2_data = file2.read()

  similarity_ratio = SequenceMatcher(None, file1_data, file2_data).ratio()
  print(similarity_ratio)

with open(r"/content/1.txt") as file1,open(r"/content/2.txt") as file2:
  file1_data = file1.read()
  file2_data = file2.read()

  similarity_ratio = SequenceMatcher(None, file1_data, file2_data).ratio()
  print(similarity_ratio)

with open(r"/content/1.txt") as file1,open(r"/content/3.txt") as file2:
  file1_data = file1.read()
  file2_data = file2.read()

  similarity_ratio = SequenceMatcher(None, file1_data, file2_data).ratio()
  print(similarity_ratio)

with open(r"/content/2.txt") as file1,open(r"/content/1.txt") as file2:
  file1_data = file1.read()
  file2_data = file2.read()

  similarity_ratio = SequenceMatcher(None, file1_data, file2_data).ratio()
  print(similarity_ratio)

with open(r"/content/2.txt") as file1,open(r"/content/2.txt") as file2:
  file1_data = file1.read()
  file2_data = file2.read()

  similarity_ratio = SequenceMatcher(None, file1_data, file2_data).ratio()
  print(similarity_ratio)

with open(r"/content/2.txt") as file1,open(r"/content/3.txt") as file2:
  file1_data = file1.read()
  file2_data = file2.read()

  similarity_ratio = SequenceMatcher(None, file1_data, file2_data).ratio()
  print(similarity_ratio)

with open(r"/content/3.txt") as file1,open(r"/content/1.txt") as file2:
  file1_data = file1.read()
  file2_data = file2.read()

  similarity_ratio = SequenceMatcher(None, file1_data, file2_data).ratio()
  print(similarity_ratio)

with open(r"/content/3.txt") as file1,open(r"/content/2.txt") as file2:
  file1_data = file1.read()
  file2_data = file2.read()

  similarity_ratio = SequenceMatcher(None, file1_data, file2_data).ratio()
  print(similarity_ratio)

with open(r"/content/3.txt") as file1,open(r"/content/3.txt") as file2:
  file1_data = file1.read()
  file2_data = file2.read()

  similarity_ratio = SequenceMatcher(None, file1_data, file2_data).ratio()
  print(similarity_ratio)